### ISSUE TITLE
In i3wm masterwidth is a pixel count not a percentage

### ISSUE THREAD

**Issue by matclab** [frap129/layman#7]
With 
```
masterWidth: 50
````

The master windows has a 50 pixels width.

**Comment by frap129** [comment]
Size is set with `resize set <masterWidth> 0 ppt`, so the only potential issue I see is that the "ppt" (percentage points) unit might need to be specified for each dimension, not just once in the command. [This commit](https://github.com/frap129/layman/commit/bb6045ba46556842760dcc2b9663d005d4f1cc67) changes the command to `resize set width <masterWidth> ppt`, which I pushed to master since it has the same behavior on sway as the previous command. I think explicitly setting width this way will work better on i3. Feel free to test and report back!

**Comment by frap129** [comment]
And thanks for putting this up on the AUR! I'll add it to the readme soon

**Comment by frap129** [comment]
Closing as stale. Feel free to reopen if it is not fixed
